title: Francisco Quintero
email: frajaquico@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer and Ruby on Rails Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.franciscoquintero.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cescquintero
github_username:  cesc1989

# Build settings
theme: minima
sass:
  sass_dir: _sass
  style: compressed
